export const DEFAULT_BINGO_PROMPTS: { text: string; category: string }[] = [
  { text: "Iemand krijgt een track cut penalty", category: "penalty" },
  { text: "Back block penalty", category: "penalty" },
  { text: "4e penalty voor dezelfde skater", category: "penalty" },
  { text: "Fouled-out skater", category: "penalty" },
  { text: "Jammer scoort 10+ punten in 1 jam", category: "jam" },
  { text: "Grand slam", category: "jam" },
  { text: "Lead jammer roept call-off onder 5 sec", category: "jam" },
  { text: "Star pass!", category: "jam" },
  { text: "Apex jump", category: "trick" },
  { text: "Skater valt en staat binnen 1 sec weer", category: "skills" },
  { text: "Iemand crasht in de penalty box", category: "fun" },
  { text: "Wall break door de jammer", category: "skills" },
  { text: "Bridge / goat", category: "strategy" },
  { text: "Power jam", category: "jam" },
  { text: "Official review", category: "officials" },
  { text: "Pivot neemt actief positie in", category: "strategy" },
  { text: "Jam eindigt 0–0", category: "jam" },
  { text: "Iemand draagt fishnets", category: "fun" },
  { text: "Glitter op de vloer", category: "fun" },
  { text: "Derby name die rijmt", category: "fun" },
  { text: "Tape op de helm", category: "fun" },
  { text: "Iemand roept &apos;JAMMER UP&apos;", category: "fun" },
  { text: "Crowd doet La Ola", category: "fun" },
  { text: "Announcer verspreekt zich", category: "fun" },
  { text: "DJ draait een cheesy 80s track", category: "fun" },
  { text: "Team huilt van de lach op de bench", category: "fun" },
  { text: "Iemand roept &apos;GO COACH&apos;", category: "fun" },
  { text: "NSO geeft een thumbs up", category: "officials" },
  { text: "Ref maakt een hartje-gebaar", category: "officials" },
  { text: "Skater valt en breakdance-staat op", category: "fun" },
  { text: "Iemand verliest een padje tijdens de jam", category: "fun" },
  { text: "Jammer rijdt achteruit de baan op", category: "skills" },
  { text: "Coach schreeuwt line-up instructies", category: "strategy" },
  { text: "Kind op de tribune doet de move na", category: "fun" },
  { text: "Tegen-team geeft een skater een hug", category: "fun" },
  { text: "Iemand scoort en doet een dansje", category: "fun" },
  { text: "Bench swap tijdens een time-out", category: "strategy" },
  { text: "Sporthal-lampje flikkert", category: "fun" },
  { text: "Iemand draagt een cape", category: "fun" },
  { text: "2 jammers raken tegelijk de jammer-line", category: "jam" },
];
